package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Package'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Package")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                schedulingPolicy = cron {
                    minutes = "50"
                    hours = "8"
                    dayOfWeek = "2-5"
                    timezone = "Australia/Perth"
                }
                branchFilter = "+:<default>"
                triggerBuild = always()
                withPendingChangesOnly = false

                enforceCleanCheckout = true
                enforceCleanCheckoutForDependencies = true
            }
        }
        trigger1.apply {
            enabled = false

        }
    }
}
